services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItem, priority: -100 }
