sylius_resource:
    resources:
        app.book:
            classes:
                model: App\Entity\NoCommerce\Book
                interface: App\Entity\NoCommerce\BookInterface
                form: App\Form\Type\BookType
                repository: App\Repository\BookRepository
                # factory: App\Factory\BookFactory
                # controller: App\Controller\BookController
            translation:
                classes:
                    model: App\Entity\NoCommerce\BookTranslation
                    interface: App\Entity\NoCommerce\BookTranslationInterface
                    form: App\Form\Type\BookTranslationType
                    # repository: App\Repository\BookTranslationRepository
                    # factory: App\Factory\BookTranslationFactory
                    # controller: App\Controller\BookTranslationController
